name: KitPvp
version: 1.0.0
main: me.bscal.starter.Main
description: KitPVP plugin
author: bscal
commands:
  events:
    usage: /<command>
    description: Starts an event
  join:
    usage: /<command>
    description: Joins an event
  start:
    usage: /<command>
    description: test
permissions:
  kitpvp.admin:
    default: op