name: KitPvp
version: 1.0.0
main: me.bscal.starter.Main
description: KitPVP plugin
author: bscal
depend: [ProtocolLib, EntityLib]
commands:
  events:
    usage: /<command>
    description: Starts an event
  join:
    usage: /<command>
    description: Joins an event
  start:
    usage: /<command>
    description: test
  soccer:
    usage: /<command>
    description: test
  pvp:
    description: Pvp Kit!
  hypebeast:
    description: Main Command